server:
  port: 9090
  servlet:
    context-path: /


spring:
  mvc:
    view:
      prefix: /WEB-INF/views/modules/
      suffix: .jsp
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

  profiles:
    active: dev

sys:
  index: /form?formView=sys/sysIndex

logging:
  level:
    com.alibaba.druid: verbose